// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: this.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	This_Ping_FullMethodName                 = "/this.This/Ping"
	This_UserRegister_FullMethodName         = "/this.This/UserRegister"
	This_UserLogin_FullMethodName            = "/this.This/UserLogin"
	This_UserLoginByPhone_FullMethodName     = "/this.This/UserLoginByPhone"
	This_UserList_FullMethodName             = "/this.This/UserList"
	This_UserPasswordRecovery_FullMethodName = "/this.This/UserPasswordRecovery"
)

// ThisClient is the client API for This service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThisClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error)
	UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	UserLoginByPhone(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	UserPasswordRecovery(ctx context.Context, in *UserPasswordRecoveryRequest, opts ...grpc.CallOption) (*UserPasswordRecoveryResponse, error)
}

type thisClient struct {
	cc grpc.ClientConnInterface
}

func NewThisClient(cc grpc.ClientConnInterface) ThisClient {
	return &thisClient{cc}
}

func (c *thisClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, This_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thisClient) UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error) {
	out := new(UserRegisterResponse)
	err := c.cc.Invoke(ctx, This_UserRegister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thisClient) UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	out := new(UserLoginResponse)
	err := c.cc.Invoke(ctx, This_UserLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thisClient) UserLoginByPhone(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	out := new(UserLoginResponse)
	err := c.cc.Invoke(ctx, This_UserLoginByPhone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thisClient) UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, This_UserList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thisClient) UserPasswordRecovery(ctx context.Context, in *UserPasswordRecoveryRequest, opts ...grpc.CallOption) (*UserPasswordRecoveryResponse, error) {
	out := new(UserPasswordRecoveryResponse)
	err := c.cc.Invoke(ctx, This_UserPasswordRecovery_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThisServer is the server API for This service.
// All implementations must embed UnimplementedThisServer
// for forward compatibility
type ThisServer interface {
	Ping(context.Context, *Request) (*Response, error)
	UserRegister(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error)
	UserLogin(context.Context, *UserLoginRequest) (*UserLoginResponse, error)
	UserLoginByPhone(context.Context, *UserLoginRequest) (*UserLoginResponse, error)
	UserList(context.Context, *UserListRequest) (*UserListResponse, error)
	UserPasswordRecovery(context.Context, *UserPasswordRecoveryRequest) (*UserPasswordRecoveryResponse, error)
	mustEmbedUnimplementedThisServer()
}

// UnimplementedThisServer must be embedded to have forward compatible implementations.
type UnimplementedThisServer struct {
}

func (UnimplementedThisServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedThisServer) UserRegister(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegister not implemented")
}
func (UnimplementedThisServer) UserLogin(context.Context, *UserLoginRequest) (*UserLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (UnimplementedThisServer) UserLoginByPhone(context.Context, *UserLoginRequest) (*UserLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLoginByPhone not implemented")
}
func (UnimplementedThisServer) UserList(context.Context, *UserListRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (UnimplementedThisServer) UserPasswordRecovery(context.Context, *UserPasswordRecoveryRequest) (*UserPasswordRecoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserPasswordRecovery not implemented")
}
func (UnimplementedThisServer) mustEmbedUnimplementedThisServer() {}

// UnsafeThisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThisServer will
// result in compilation errors.
type UnsafeThisServer interface {
	mustEmbedUnimplementedThisServer()
}

func RegisterThisServer(s grpc.ServiceRegistrar, srv ThisServer) {
	s.RegisterService(&This_ServiceDesc, srv)
}

func _This_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThisServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: This_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThisServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _This_UserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThisServer).UserRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: This_UserRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThisServer).UserRegister(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _This_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThisServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: This_UserLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThisServer).UserLogin(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _This_UserLoginByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThisServer).UserLoginByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: This_UserLoginByPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThisServer).UserLoginByPhone(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _This_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThisServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: This_UserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThisServer).UserList(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _This_UserPasswordRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPasswordRecoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThisServer).UserPasswordRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: This_UserPasswordRecovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThisServer).UserPasswordRecovery(ctx, req.(*UserPasswordRecoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// This_ServiceDesc is the grpc.ServiceDesc for This service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var This_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "this.This",
	HandlerType: (*ThisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _This_Ping_Handler,
		},
		{
			MethodName: "UserRegister",
			Handler:    _This_UserRegister_Handler,
		},
		{
			MethodName: "UserLogin",
			Handler:    _This_UserLogin_Handler,
		},
		{
			MethodName: "UserLoginByPhone",
			Handler:    _This_UserLoginByPhone_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _This_UserList_Handler,
		},
		{
			MethodName: "UserPasswordRecovery",
			Handler:    _This_UserPasswordRecovery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "this.proto",
}
